# Generated by Django 5.0.6 on 2024-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ManyToManyField(related_name='status_tasks', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='type_tasks', to='webapp.type', verbose_name='Тип'),
        ),
    ]
