# Generated by Django 5.0.6 on 2024-07-20 13:25

from django.db import migrations


def create_test_project(apps, schema_editor):
    Project = apps.get_model('webapp.Project')
    Task = apps.get_model('webapp.Task')
    project = Project.objects.create(
        start_date='2024-01-01',
        name='Проект по улучшению приложения',
        description='Проект содержит задачи, связанные с улучшением функциональности и производительности приложения.'
    )
    Task.objects.update(project=project)


def delete_test_project(apps, schema_editor):
    Project = apps.get_model('webapp.Project')
    Task = apps.get_model('webapp.Task')
    project = Project.objects.get(name='Проект по улучшению приложения')
    Task.objects.filter(project=project).update(project=None)
    project.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0006_project_task_project'),
    ]

    operations = [
        migrations.RunPython(create_test_project, delete_test_project),
    ]
